\documentclass[review, doubleblind, 3p,
authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{Computers, Environment and Urban Studies} % Sets Journal name

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
% TODO: Currently lineno needs to be loaded after amsmath because of conflict
% https://github.com/latex-lineno/lineno/issues/5
\usepackage{lineno} % add
  \linenumbers % turns line numbering on
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}

\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Modeling the impacts of replacing car trips with combined public transport and cycling: Reproducible methods, results and actionable evidence from biclaR},
            colorlinks=true,
            urlcolor=blue,
            linkcolor=blue,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


% Pandoc citation processing
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}


\usepackage{subfig}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\biboptions{authoryear}
\usepackage{url}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{makecell}
\usepackage{multirow}

\begin{document}


\begin{frontmatter}

  \title{Modeling the impacts of replacing car trips with combined
public transport and cycling: Reproducible methods, results and
actionable evidence from biclaR}
    \author[CERIS]{Rosa Félix\corref{cor1}%
  \corref{cor1}%
  }
   \ead{rosamfelix@tecnico.ulisboa.pt} 
    \author[CERIS]{Filipe Moura%
  %
  }
   \ead{fmoura@tecnico.ulisboa.pt} 
    \author[ITS]{Robin Lovelace%
  %
  }
   \ead{r.lovelace@uleeds.uk} 
      \affiliation[CERIS]{CERIS, Instituto Superior Técnico -
Universidade de Lisboa, Av Rovisco Pais 1, 1049-001 Lisboa, Portugal}
    \affiliation[ITS]{Institute for Transport Studies, University of
Leeds. 34-40 University Rd, Leeds LS2 9JT, UK}
    \cortext[cor1]{Corresponding author}
  
  \begin{abstract}
  A high proportion of car trips can be replaced by a combination of
  public transit and cycling for the first-and-last mile. This paper
  estimates the potential for cycling combined with public transit as a
  substitute for car trips in the Lisbon metropolitan area and assesses
  its socio-environmental impacts using open data and open source tools.
  A decision support tool that facilitates the design and development of
  a metropolitan cycling network was developed (\emph{biclaR}). The
  social and environmental impacts were assessed using the \emph{HEAT
  for Cycling} and the \emph{HEAT as a Service} tools. The impacts of
  shifting car trips to public transport were also estimated and
  monetized. The results show that 10\% of all trips could be made by
  cycling in combination with public transport. Shifting to cycling for
  the shorter first and last mile stages can reduce annual
  CO\textsubscript{2}eq emissions from 3,000 to 7,500 tons/day, while
  for the public transport leg, the transfer from car avoids of up to
  20,500 tons of CO\textsubscript{2}eq emissions per year. The estimated
  socio-environmental benefits are of €125 million to €325 million over
  10 years. This evidence can support policymakers to prioritize
  interventions that reduce the reliance on private motor vehicles.\\
  \end{abstract}
    \begin{keyword}
    Active transport \sep Intermodality \sep First and last
mile \sep Health economic assessment \sep Environmental impacts \sep 
    Open data and methods
  \end{keyword}
  
 \end{frontmatter}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Combining public transportation (PT) and cycling for the first and last
mile in metropolitan areas can replace a high proportion of private car
trips (Martens, 2007). In The Netherlands, which has the highest mode
share of cycling in the world, cycling accounts for more than a third of
all trips to and from rail stations at the `home' end of the journey,
greatly increasing the ability of the transport system (Rietveld, 2000).
This approach to reducing car dependency and associated externalities
requires interventions and programs to make bicycling more appealing (La
Paix et al., 2021). The resulting public investments can have
significant social and environmental benefits (International Transport
Forum, 2017). Despite the benefits of cycling-PT intermodality, the
potential of this combination is often overlooked in transport planning
(La Paix et al., 2021).

The potential of cycling as a complementary mode of PT is substantial
worldwide, especially in cities with established public transport
networks or substantial ambitions to develop them. In the Lisbon
metropolitan area (LMA) the largest metropolitan area in Portugal, the
modal share of cycling is low, but the potential for cycling as a
complementary mode of PT is high. According to the latest mobility
survey conducted in 2018 (INE, 2018), the LMA registered a total of 5.3
million daily trips, with only 0.5\% by bicycle. Car modal share was
58.4\%, while PT accounted for 15.5\% (see Figure \ref{fig:mododist}).
The number of intra-municipal trips --- with origin and destination in
the same municipality --- amounts to 3.5 million trips. This exceeds the
number of inter-municipal trips (1.8 million trips), involving travel
between different municipalities. Cars and public transport are the most
used modes for intercity trips, with cars being the predominant choice
for all journeys.\\
53\% trips are up to 5 km distance, and 71\% up to 10 km. Nevertheless,
29\% of trips are longer than 10 km, which requires the use of motorized
modes, or active modes in combination with public transport.

\begin{figure}
\subfloat[In percentage\label{fig:mododist-1}]{\includegraphics[width=0.5\linewidth,]{PaperCEUS_files/figure-latex/mododist-1} }\subfloat[In total\label{fig:mododist-2}]{\includegraphics[width=0.5\linewidth,]{PaperCEUS_files/figure-latex/mododist-2} }\caption{\label{mododist}Trips in the LMA by inter/intra municipal and mode, according to the travel survey.}\label{fig:mododist}
\end{figure}

To achieve the cycling targets set by the Portuguese national cycling
strategy for 2025 and 2030 (4\% and 10\%, respectively) (Presidência do
Conselho de Ministros, 2019), the Lisbon's Metropolitan Department of
Transport commissioned \emph{biclaR}\footnote{See
  \href{https://biclar.tmlmobilidade.pt/}{biclar.tmlmobilidade.pt}.}, a
decision support tool that facilitates the planning, design, and
development of a metropolitan cycling network (Félix et al., 2022).

\emph{biclaR} builds on the Propensity to Cycle Tool\footnote{See
  \href{https://www.pct.bike/}{pct.bike}.} (PCT), a web application and
research project funded by the UK's Department for Transport in 2015
which launched nationally in 2017 as part of the government's Cycling
and Walking Investment Strategy. The PCT initially used only
origin-destination data for commuting trips as the basis of estimates of
cycling potential at zone, route and route network levels (Lovelace et
al., 2017). The PCT has been extended to include cycling potential for
travel to school in England (Goodman et al., 2019) and other trip types
in other countries.\footnote{See \href{https://www.npt.scot}{npt.scot}
  and \href{https://cruse.bike}{cruse.bike} for examples of the PCT in
  Scotland and Ireland that include estimates of cycling for other
  purposes.} However, to the best of our knowledge, this is the first
time that the method has been integrated with public transport data
using multi-modal routing to estimate the potential and benefits of
multi-stage cycling and PT trips.

This paper estimates the potential for combining cycling and PT to
substitute car trips in the LMA, while achieving the national cycling
targets. After presenting the methods used, it assesses its
socio-environmental impacts using open data and open-source tools.

\hypertarget{methods}{%
\section{Methods}\label{methods}}

\hypertarget{modeling-origin-destination-trips}{%
\subsection{Modeling Origin-Destination
trips}\label{modeling-origin-destination-trips}}

The mobility survey data (INE, 2018) is the basis of the baseline
scenario and trip rates presented in this paper. Conducted in the
pre-pandemic period (2017), this OD dataset represents the most
comprehensive and up-to-date information on urban mobility in Portuguese
metropolitan areas (Lisbon and Porto).

We used `jittering' to disaggregate the OD data, resulting in a wide
spatial distribution of trip origins and destinations (Lovelace et al.,
2022b). The method works by sampling `sub-points' (nodes on the
transport network represented in OpenStreetMap in this case) and using
these instead of a single point (typically the centroid) to represent
trip origins and destinations for each zone. This method then
distributes the trips to desire lines connecting the subpoints based on
a `disaggregation threshold' which determines the maximum number of
trips that can be represented by a single desire line.

Using the
\href{https://github.com/dabreegster/odjitter}{\texttt{odjitter} R
package}, we disaggregated the OD data into desire lines reprenting a
maximum of 100 trips each. Figure \ref{fig:jitter} illustrates the
contrast between trip representation through the traditional method,
which connects a single desire line between each district, and the
presentation achieved through the randomization and disaggregation of
trips between districts, specifically for the Lisbon metropolitan area.

\begin{figure}

{\centering \includegraphics[width=1\linewidth,]{img/jitter} 

}

\caption{Representation of desire lines in the Lisbon metropolitan area between districts, without jittering (left) and with jittering (right).}\label{fig:jitter}
\end{figure}

The jittering pre-processing stage generates a more realistic
representation of the trips undertaken than the traditional
centroid-based approach but does not precisely capture the exact spatial
distribution of trips. Even where such datasets exist, they cannot be
shared for research due to data privacy regulations.

\hypertarget{modeling-routes}{%
\subsection{Modeling routes}\label{modeling-routes}}

The mobility survey collects the origin and destination of trips but
does not include the respective routes. Modeling the realistic
cycling-PT routes between OD pairs depends on assumptions regarding the
characteristics of the cycling and road networks and the location of
public transport interfaces. Other constraints regarding the behavior of
potential cyclists determine the routing results. For example, such
restrictions can favor low speed, low traffic streets, more direct
routes, and less steep paths, among others, which are suitable for
cycling.

The selected route choice algorithm was the
\href{https://ipeagit.github.io/r5r/}{\texttt{r5r} R package} (Pereira
et al., 2021), which allows for great flexibility in configuring
estimated route types, and which proven to provide most accurate route
networks for the city of Lisbon (Lovelace et al., 2022a). \texttt{r5r}
can calculate multi-modal routes using PT combined with other modes. It
enables the identification of the most direct or safest cycling routes,
using the Level of Traffic Stress\footnote{see
  \href{https://docs.conveyal.com/learn-more/traffic-stress}{docs.conveyal.com/learn-more/traffic-stress}.}
(LTS) scale, ranging from 1 to 4, where 1 corresponds to the quietest
(e.g., off-road cycle paths) and 4 corresponds to the least quiet (e.g.,
routes shared with motorized traffic). The routes were estimated for the
base scenario for both types of networks: \emph{direct} and \emph{safe},
using LTS 4 and LTS 3, respectively. Different routing profiles enable
decision-makers to plan for different bicycle user typologies and/or for
different city cycling maturity levels (Félix et al., 2017).

The \texttt{r5r} model used the OpenStreetMap road network and the GTFS
metropolitan data aggregated and validated. This information is crucial
for an accurate PT trip and route estimation. A digital elevation model,
from the European Space Agency's COPERNICUS mission, was used to include
street gradient information, as a weight in cycling routing. The cycling
potential trips for the two national strategic targets (4\% and 10\%)
were estimated from the 2017 cycling and car trips (both as a driver and
as a passenger), the baseline scenario.

The routes were then overlaid and aggregated by segments, using
\href{https://docs.ropensci.org/stplanr/reference/overline.html}{\texttt{stplanr\ overline()}
R function}.

\hypertarget{modeling-intermodality}{%
\subsection{Modeling intermodality}\label{modeling-intermodality}}

The intermodality scenario considers trips made by PT in which cycling
is used for the first and last legs. We restricted our analysis to the
first and last legs with a combined length of up to 5 km (for example: 1
km from origin to interface \emph{A} plus 4 km from interface \emph{B}
to destination) or up to 25 minutes on bike travel-time. This
conservative approach was adopted to capture the fact that cycling
stages as part of a multi-modal trip are likely to be shorter than
cycling-only trips (van Mil et al., 2021). Furthermore, we have imposed
restrictions on PT usage, limiting it to trips without PT transfers, and
within a duration of up to 2 hours (120 minutes). Additionally, we have
only included PT modes that can easily accommodate bicycles, such as
trains, ferries, trams, and inter-municipal bus lines equipped with bike
racks (Figure \ref{fig:map1}). These restrictions can be eased in the
future when testing more developed policy interventions to enhance
intermodality between cycling and PT, considering both the vehicle and
infrastructure perspectives.

\begin{figure}

{\centering \includegraphics[width=0.6\linewidth,]{img/map1} 

}

\caption{Interfaces and lines considered, by transport mode, in the Lisbon metropolitan area.}\label{fig:map1}
\end{figure}

Figure \ref{fig:map2} illustrates the resulting bicycle routes to access
the main PT interfaces in the LMA.

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth,]{img/map2} 

}

\caption{Bike routes with the highest potential to serve as first and last leg when replacing cycling and PT from car trips (screenshot of the interactive online tool).}\label{fig:map2}
\end{figure}

\hypertarget{assessing-socio-environmental-benefits}{%
\subsection{Assessing socio-environmental
benefits}\label{assessing-socio-environmental-benefits}}

For the \emph{cycling legs of the journey} (first and last legs),
socio-environmental impacts were estimated, using the Health Economic
Assessment Tool (HEAT) for Cycling v5.2 (Kahlmeier et al., 2017), from
the World Health Organization, and the
\href{https://github.com/HEAT-WHO/HEAT_heatr_api}{\texttt{HEATaaS} R
package}\footnote{\texttt{HEATaaS} is under development. For more
  information contact
  \href{https://heatwalkingcycling.org}{heatwalkingcycling.org}.}. The
use of this package made it possible to run multiple scenarios with few
changes in input values, making the interaction with HEAT more reliable
when reproducing runs.\\
The HEAT tool provided estimates on the shifting from car to cycling for
a short term time horizon (i.e., one year) and the long term (i.e., ten
years). It estimates the differences between two considered scenarios.
In this case: one baseline scenario, with data from the mobility survey,
and one cycling potential scenario in which targets of 4\% and 10\% of
cycling levels were achieved, transferred from car trips. We considered
two dimensions: \emph{social} --- including the physical activity, air
pollution exposure, and road casualties; and \emph{environmental} ---
including CO\textsubscript{2}eq emissions and other pollutants.

For the \emph{second leg of the journey}, we estimate the environmental
impacts of shifting car trips to PT (between the PT interfaces).

To estimate the car emissions, we used the EMEP/EEA's COPERT software v5
methods and reference values (Ntziachristos \& Samaras, 2020) for a Tier
3 detail level. We used a family-size vehicle, EURO standard, and
gasoline or diesel fuel. All trips were considered to be made under
urban conditions and at an average speed of 15 km/h during rush hour
periods. Since the average distance traveled per trip influences the
overconsumption and emissions from cold-start engine operation, we
estimated energy and emission factors for different ranges of trips at
500-meter intervals.\\
An equation was then used to calculate emission factors for the two
types of fuel, for each type of pollutant, whose explanatory variables
are driving speed (\(speed\), in km/h) and average trip distance
(\(l_{trip}\), in km/trip). Thus, the emission factors
(\(EF_{fuel,l_{trip},speed}\), in g/km) can be calculated using equation
\ref{eq:fatoremissaoauto}.

\begin{equation}\label{eq:fatoremissaoauto}
{EF}_{fuel,l_{trip},speed} = a + b\cdot {speed} + c\cdot l_{trip}
\end{equation}

Emission factors are estimated for the following air pollutants: CO,
NO\textsubscript{X}, VOC, and PM\textsubscript{10}. Emission factors of
the main greenhouse gases (GHG) are also estimated: CO\textsubscript{2},
CH\textsubscript{4} and N\textsubscript{2}O, converted in
CO\textsubscript{2}eq by the following relationship\footnote{The weights
  correspond to the Global Warming Potentials (GWP) defined for a
  100-year period by the IPCC in its
  \href{https://www.ipcc.ch/report/ar5/}{5th Assessment Report}.}:
\(EF_{CO_2eq} = EF_{CO_2} + 28\cdot EF_{CH_4} + 265\cdot EF_{N_2O}\).
The CH\textsubscript{4} and N\textsubscript{2}O emission factors do not
vary with travel speed. The PM\textsubscript{10} emission factor does
not vary with trip distance.

The used values consider that 64\% of the car fleet was diesel in
2022\footnote{See
  \href{https://smi.ine.pt/Indicador/Detalhes/10837?LANG=EN}{Statistics
  Portugal: Stock road vehicles statistic}.}. In addition, we assumed an
occupancy rate of 1.6 passengers \emph{per} car (INE, 2018). Finally,
the final emissions for each trip (\(E_{pollutant}\), in g/trip) are
derived from the equation \ref{eq:emissaoauto}.

\begin{equation}\label{eq:emissaoauto}
{E}_{pollutant} = {EF}_{fuel,l_{trip},speed}\cdot l_{trip}
\end{equation}

Regarding PT, we considered the emission factor values reported in the
environmental and sustainability reports of the PT operators in the LMA
(Carris, 2020; CP, 2020; Metropolitano de Lisboa, 2020; Transtejo,
2014). In particular, for the urban train and tram -- with 100\%
electric traction -- only CO\textsubscript{2}eq emissions were
considered (resulting from the production of electricity, considering a
``well-to-tank'' approach), since the other pollutants are not emitted
locally.

The conversion of avoided emissions into avoided welfare loss and
respective monetary valuation was based on the EU Guide to Cost-benefit
Analysis (Sartori et al., 2014) and the best up-to-date reference values
for the various gases (Bickel et al., 2006; Nash et al., 2003; Sartori
et al., 2014): 8.44 €/ton for CO, 2,867.85 €/ton for
NO\textsubscript{X}, 340,969.27 €/ton for PM\textsubscript{10}, 7,169.62
€/ton for VOC and 35.85 €/ton for CO\textsubscript{2}eq. The social
impacts are in avoided premature mortality. This result is finally
monetized using the \emph{Statistical Value of Life} for Portugal:
€3,055,358/fatality (Silva et al., 2021). We updated all the monetary
reference values of the literature based on the annual inflation rate in
Portugal for 2022\footnote{See
  \href{https://www.ine.pt/xportal/xmain?xpid=INE\&xpgid=ipc}{Statistics
  Portugal tool for inflation rate estimates between years}.}, and our
10-years estimations assumed a discount rate of 5\% and inflation of
3\%. See \protect\hyperlink{research-data}{Research Data} for all the
input values we used.

\hypertarget{results-and-discussion}{%
\section{Results and Discussion}\label{results-and-discussion}}

Table \ref{tab:summary1} presents the LMA total daily trips that can be
made with cycling + TP combination (with the aforementioned
restrictions), the trips in the baseline scenario and corresponding new
trips to achieve the national strategy targets (4\% and 10\%), for
different route profiles. For the cycling legs of the journey (first and
last legs), the environmental avoided emissions and monetized
socio-environment (SE) benefits are presented in Table
\ref{tab:summary1b}, resulting from replacing car trips with cycling.

\begin{table}

\caption{\label{tab:summary1}\label{summary1}Summary of the cycling potencial of the intermodality scenario.}
\centering
\begin{tabular}[t]{llr>{\raggedleft\arraybackslash}p{7em}>{\raggedleft\arraybackslash}p{7em}}
\toprule
Target & Routing & Total trips & Baseline Cycling + PT & Potencial Cycling + PT\\
\midrule
4\% & safe & 538 514 & 2 312 & 20 385\\
4\% & direct & 500 880 & 2 274 & 18 944\\
10\% & safe & 538 514 & 2 312 & 52 323\\
10\% & direct & 500 880 & 2 274 & 48 609\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:summary1b}\label{summary1b}Summary of the cycling potencial of intermodality scenario and its socio-environmental benefits for the cycling legs.}
\centering
\begin{tabular}[t]{ll>{\raggedleft\arraybackslash}p{6em}>{\raggedleft\arraybackslash}p{6em}>{\raggedleft\arraybackslash}p{6em}>{\raggedleft\arraybackslash}p{6em}}
\toprule
Target & Routing & Avoided Mortality (deaths/yr) & Social benefits (k€/yr) & Avoided CO2eq (ton/yr) & Environmental benefits (k€/yr)\\
\midrule
4\% & safe & 4.1 & 12 717 & 2 958 & 238\\
4\% & direct & 4.0 & 12 441 & 3 004 & 241\\
10\% & safe & 10.0 & 32 820 & 7 590 & 610\\
10\% & direct & 10.0 & 31 800 & 7 694 & 618\\
\bottomrule
\end{tabular}
\end{table}

For both \emph{direct} and \emph{safe} route profiles, 10\% of the daily
trips have the potential to be made by a combination of PT and cycling,
even given the travel restrictions considered (up to 5 km on bike, up to
2 hours, no possible transfers between PT). This unveils the potential
of cycling as a complementary mode of PT, with the potential to uptake
the number of PT trips within the LMA area by as much as 6.3\% (in
addition to the 825 thousand PT trips reported in the mobility survey).

Table \ref{tab:summary21} shows the potential trips by PT mode to
replace the second leg of the journey, in combination with cycling.
Train offers the greatest potential for substitution (88\%). When
comparing the existing PT interfaces (Figure \ref{fig:map1}) with the
bike routes with highest potential to serve as first and last legs
(Figure \ref{fig:map2}) it becomes clear that the Train interfaces are
the ones that have the highest potential to attract car-to-PT
substituting trips, if their accessibility by bicycle is improved to
become safer.

\begin{table}

\caption{\label{tab:summary21}\label{summary21}Summary of the potential of replacing car trips with cycling in combination with PT, disagregated by PT mode.}
\centering
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{4.5em}>{\raggedright\arraybackslash}p{4.5em}>{\raggedleft\arraybackslash}p{4.5em}>{\raggedleft\arraybackslash}p{4.5em}>{\raggedleft\arraybackslash}p{4.5em}>{\raggedleft\arraybackslash}p{4.5em}>{\raggedleft\arraybackslash}p{4.5em}}
\toprule
Target & Routing & Potential & Bus & Ferry & Train & Tram\\
\midrule
4\% & safe & 20 385 & 573 & 285 & 17 716 & 1 811\\
4\% & direct & 18 944 & 593 & 313 & 17 093 & 946\\
10\% & safe & 52 323 & 1 452 & 712 & 45 588 & 4 571\\
10\% & direct & 48 609 & 1 520 & 781 & 43 932 & 2 375\\
\bottomrule
\end{tabular}
\end{table}

Table \ref{tab:summary22} presents emissions reductions and associated
economic benefits associated with the second (PT) leg of trips. The
shift from private car associated with thes PT segments would reduce
CO\textsubscript{2} equivalent emissions by 8,500 to 20,800 tons
annually, valued in €1.4 million to €3.5 million yearly, for the 4\% and
10\% targets, respectively.

\begin{table}

\caption{\label{tab:summary22}\label{summary22}Summary of the avoided emmissions (ton/year) and corresponding monetization (thousand €) by replacing car trips with PT, in the second leg.}
\centering
\begin{tabular}[t]{ll>{\raggedleft\arraybackslash}p{3.5em}>{\raggedleft\arraybackslash}p{3.5em}>{\raggedleft\arraybackslash}p{3.5em}>{\raggedleft\arraybackslash}p{3.5em}>{\raggedleft\arraybackslash}p{3.5em}r}
\toprule
Target & Routing & CO2eq & CO & PM10 & NOx & VOC & Value (k€)\\
\midrule
4\% & safe & 8 593 & 17 & 1.9 & 27 & 0.8 & 1 425\\
4\% & direct & 8 702 & 18 & 2.0 & 28 & 0.8 & 1 453\\
10\% & safe & 20 627 & 42 & 4.6 & 65 & 2.0 & 3 431\\
10\% & direct & 20 793 & 42 & 4.7 & 66 & 1.9 & 3 487\\
\bottomrule
\end{tabular}
\end{table}

The sum of CO\textsubscript{2}eq avoided emissions from the potential
car trips shifted to bike (first-and-last legs) in combination with PT
(second leg) in the LMA is presented in Table \ref{tab:summaryall}, for
both national cycling strategy targets and routing profiles, and the
socio-environmental benefits monetized in €, for a 1-year and 10-year
time periods.

\begin{table}

\caption{\label{tab:summaryall}\label{summaryall}Summary of the avoided CO2eq emmissions (ton/year) and the estimated social and environmental benefits (monetized in thousand €) by replacing car trips with cycling in combination with PT.}
\centering
\begin{tabular}[t]{ll>{\raggedleft\arraybackslash}p{8em}>{\raggedleft\arraybackslash}p{8em}>{\raggedleft\arraybackslash}p{8em}}
\toprule
Target & Routing & Avoided CO2eq (tons) & SE Benefits 1yr (k€) & SE Benefits 10yrs (k€)\\
\midrule
4\% & safe & 11 551 & 14 380 & 127 534\\
4\% & direct & 11 706 & 14 135 & 125 016\\
10\% & safe & 28 217 & 36 861 & 325 814\\
10\% & direct & 28 487 & 35 905 & 318 062\\
\bottomrule
\end{tabular}
\end{table}

Shifting from car to cycling in combination with PT can reduce annual
CO\textsubscript{2}eq emissions by 11,500 to 28,500 tons per year. These
figures represent a 2.7\% reduction in Lisbon's transport emissions
(Lisboa E-Nova, 2023), a small but important component of wider
transport decarbonization measures. The 10-year socio-environmental
benefits account for €125 million to €325 million, depending on the
cycling targets.

The environmental impacts represent less than 2\% of the
socio-environmental benefits (in value) from replacing car trips to
bicycle in first-and-last legs. For the PT segment, we did not estimate
the social impacts from substituting car trips. One of the main
socio-environmetal benefits, valued after monetization, comes from the
increase in physical activity (Félix et al., 2023). Although there are
also social benefits form shifting car trips to PT, its health benefits
would not be as high as shifting to cycling. The literature shows that
the Metabolic Equivalent Tasks (MET) for ``riding in a bus or a train''
is 1.3 plus the ``walking for transportation'' as 3.5, while ``driving a
car'' is 2.5 (Ainsworth et al., 2011). The difference between these
activities - shifting from car to PT - is not very obvious when compared
to shifting from car to cycling, whose MET is about 6.8. Nevertheless,
future works should also encompass the estimation of the social impacts
for the PT leg of the journey, shifting from car.

The emissions of CO\textsubscript{2}eq that are avoided during both the
initial and final journey segments account for about 74\% of the
emissions avoided during the PT segment. This finding, while expected --
due the zero cycling emissions, should not be overlooked when promoting
the PT use. Improving the safe accessibility to PT interfaces to
cyclists and providing bicycle-friendly amenities such as parking
facilities can potentially lead to a higher reduction in
CO\textsubscript{2}eq emissions, compared to a scenario where
individuals shift from car travel to car + PT combination.

Our findings show that cycling \emph{in combination} with PT could
replace 10\% of current LMA trips, with an additional 6\% of PT journeys
prone to further substitution, based on conservative assumptions.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

This paper estimated the potential for combining cycling and PT to
substitute car trips in the LMA, while achieving the national cycling
targets and supporting decarbonization goals. It has become
progressively more common to establish strategic plans, at national,
regional or municipal level, to mitigate climate change. Among these,
the Sustainable Urban Mobility Plans (SUMP\footnote{See
  \href{https://www.eltis.org/mobility-plans/sump-concept}{eltis.org/mobility-plans/sump-concept}}),
promoted by the European Commission, are becoming popular in Europe,
although authorities are designing documents of this sort all over the
world. The definition of targets associated with a timeframe for
reducing dependence on the individual motorized vehicle, or targets for
the use of active modes such as walking and cycling, are too often not
accompanied by estimates of their social, environmental and economic
impacts. It is important for authorities and practitioners to know how
to estimate those impacts, which tools are available to support them in
the process, and what results to expect.

This paper quantifies the benefits of replacing car trips with cycling,
in combination with public transport. The case study of the Lisbon
metropolitan area demonstrates that cycling-PT integration can help meet
the national targets set for bicycle use of 4\% and 10\% by 2025 and
2030, respectively.

The quantification of benefits can support policy-makers in prioritizing
interventions to reduce the reliance on private motorized modes of
transportation. The presentation of the results in an open access web
application will help to inform and explain decisions. Furthermore, the
provision of datasets resulting from this project provides a foundation
for further research and development of new tools and methods. The
methods are reproducible and based on open source software, which can be
applied to other cities and metropolitan areas, supporting the
decarbonization of transport systems internationally.

\hypertarget{acknowledgements}{%
\section*{Acknowledgements}\label{acknowledgements}}
\addcontentsline{toc}{section}{Acknowledgements}

{[}\emph{blind}{]}

\hypertarget{research-data}{%
\section*{Research data}\label{research-data}}
\addcontentsline{toc}{section}{Research data}

The data and the code to reproduce the results will be made available
upon publication.

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-MET2011}{}}%
Ainsworth, B. E., Haskell, W. L., Herrmann, S. D., Meckes, N., Bassett
Jr, D. R., Tudor-Locke, C., Greer, J. L., Vezina, J., Whitt-Glover, M.
C., \& Leon, A. S. (2011). {2011 Compendium of Physical Activities: A
second update of codes and MET values}. \emph{Medicine \& Science in
Sports \& Exercise}, \emph{43}(8), 1575--1581.
\url{https://doi.org/10.1249/MSS.0b013e31821ece12}

\leavevmode\vadjust pre{\hypertarget{ref-bickel2006}{}}%
Bickel, P., Friedrich, R., Burgess, A., Fagiani, P., Hunt, A., Jong, G.
D., \& Laird, J. (2006). \emph{{HEATCO - Developing Harmonised European
Approaches for Transport Costing and Project Assessment. Deliverable 5,
Proposal for Harmonised Guidelines.}}
\url{https://trimis.ec.europa.eu/sites/default/files/project/documents/20130122_113653_88902_HEATCO_D5_summary.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-Carris2019s}{}}%
Carris. (2020). \emph{Relatório de sustentabilidade 2019 - demostração
não financeira}. {Carris - Companhia Carris de Ferro de Lisboa, E.M.,
S.A.} \url{https://www.carris.pt/media/dkdp2wbg/dnf_carris2019_rv5.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-CP2019s}{}}%
CP. (2020). \emph{Relatório de sustentabilidade 2019}. {CP - Comboios de
Portugal, E.P.E.}
\url{https://www.cp.pt/StaticFiles/Institucional/2_gestao_sustentavel/1_RelatoriosSustentabilidade/relatorio-de-sustentabilidade-2019.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-felix2023}{}}%
Félix, R., Lovelace, R., \& Moura, F. (2022). \emph{{biclaR - Ferramenta
de apoio ao planeamento da rede ciclável na área metropolitana de
Lisboa}}. {CERIS - Instituto Superior Técnico and Transportes
Metropolitanos de Lisboa}. \url{https://biclar.tmlmobilidade.pt}

\leavevmode\vadjust pre{\hypertarget{ref-felix2017}{}}%
Félix, R., Moura, F., \& Clifton, K. J. (2017). Typologies of urban
cyclists: Review of market segmentation methods for planning practice.
\emph{Transportation Research Record}, \emph{2662}(1), 125--133.
\url{https://doi.org/10.3141/2662-14}

\leavevmode\vadjust pre{\hypertarget{ref-Felix2023ES}{}}%
Félix, R., Orozco-Fontalvo, M., \& Moura, F. (2023). Socio-economic
assessment of shared e-scooters: Do the benefits overcome the
externalities? \emph{Transportation Research Part D: Transport and
Environment}, \emph{118}, 103714.
\url{https://doi.org/10.1016/j.trd.2023.103714}

\leavevmode\vadjust pre{\hypertarget{ref-goodman2019}{}}%
Goodman, A., Rojas, I. F., Woodcock, J., Aldred, R., Berkoff, N.,
Morgan, M., Abbas, A., \& Lovelace, R. (2019). Scenarios of cycling to
school in england, and associated health and carbon impacts: Application
of the {`}propensity to cycle tool{'}. \emph{Journal of Transport \&
Health}, \emph{12}, 263--278.
\url{https://doi.org/10.1016/j.jth.2019.01.008}

\leavevmode\vadjust pre{\hypertarget{ref-IMOB}{}}%
INE. (2018). \emph{Mobilidade e funcionalidade do território nas {Áreas
Metropolitanas do Porto e de Lisboa}: 2017}. {Instituto National de
Estatística}.
\url{https://www.ine.pt/xportal/xmain?xpid=INE\&xpgid=ine_publicacoes\&PUBLICACOESpub_boui=349495406\&PUBLICACOESmodo=2\&xlang=pt}

\leavevmode\vadjust pre{\hypertarget{ref-internationaltransportforum_integrating_2017}{}}%
International Transport Forum. (2017). \emph{Integrating {Urban Public
Transport Systems} and {Cycling}}. {Organisation for Economic
Co-operation and Development}.

\leavevmode\vadjust pre{\hypertarget{ref-HEAT}{}}%
Kahlmeier, S., Götschi, T., Cavill, N., Castro Fernandez, A., Brand, C.,
Rojas Rueda, D., Woodcock, J., Kelly, P., Lieb, C., Oja, P., et al.
(2017). \emph{Health economic assessment tool ({HEAT}) for walking and
for cycling: Methods and user guide on physical activity, air pollution,
injuries and carbon impact assessments}.
\url{https://www.euro.who.int/__data/assets/pdf_file/0010/352963/Heat.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-lapaix_role_2021}{}}%
La Paix, L., Cherchi, E., \& Geurs, K. (2021). Role of perception of
bicycle infrastructure on the choice of the bicycle as a train feeder
mode. \emph{International Journal of Sustainable Transportation},
\emph{15}(6), 486--499.
\url{https://doi.org/10.1080/15568318.2020.1765223}

\leavevmode\vadjust pre{\hypertarget{ref-LisboaENova}{}}%
Lisboa E-Nova. (2023). \emph{{Observatórios Lisboa - Infos Emissões
Gases com Efeito Estufa}}. {Agência de Energia e Ambiente de Lisboa}.
\url{https://observatorios-lisboa.pt/info_emissoes.html}

\leavevmode\vadjust pre{\hypertarget{ref-Lovelace2022exploring}{}}%
Lovelace, R., Félix, R., \& Carlino, D. (2022a). Exploring jittering and
routing options for converting origin-destination data into route
networks: Towards accurate estimates of movement at the street level.
\emph{The International Archives of the Photogrammetry, Remote Sensing
and Spatial Information Sciences}, \emph{XLVIII-4/W1-2022}, 279--286.
\url{https://doi.org/10.5194/isprs-archives-XLVIII-4-W1-2022-279-2022}

\leavevmode\vadjust pre{\hypertarget{ref-Lovelace2022Jittering}{}}%
Lovelace, R., Félix, R., \& Carlino, D. (2022b). Jittering: A
computationally efficient method for generating realistic route networks
from origin-destination data. \emph{Findings}.
\url{https://doi.org/10.32866/001c.33873}

\leavevmode\vadjust pre{\hypertarget{ref-lovelace2017}{}}%
Lovelace, R., Goodman, A., Aldred, R., Berkoff, N., Abbas, A., \&
Woodcock, J. (2017). The Propensity to Cycle Tool: An open source online
system for sustainable transport planning. \emph{Journal of Transport
and Land Use}, \emph{10}(1). \url{https://doi.org/10.5198/jtlu.2016.862}

\leavevmode\vadjust pre{\hypertarget{ref-MARTENS2007326}{}}%
Martens, K. (2007). Promoting bike-and-ride: The dutch experience.
\emph{Transportation Research Part A: Policy and Practice},
\emph{41}(4), 326--338. \url{https://doi.org/10.1016/j.tra.2006.09.010}

\leavevmode\vadjust pre{\hypertarget{ref-Metro2019s}{}}%
Metropolitano de Lisboa. (2020). \emph{Relatório integrado 2019}.
{Metropolitano de Lisboa, E.P.E.}
\url{https://www.metrolisboa.pt/wp-content/uploads/2021/01/relatorio_integrado_2019.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-UNITE}{}}%
Nash, C. et al. (2003). \emph{UNIfication of accounts and marginal costs
for transport efficiency: Final report}. {Institute for Transport
Studies, University of Leeds}.
\url{https://www.its.leeds.ac.uk/projects/unite/downloads/Unite\%20Final\%20Report.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-COPERT}{}}%
Ntziachristos, L., \& Samaras, Z. (2020). \emph{{EMEP/EEA} air pollutant
emission inventory guidebook 2019}. Luxembourg: European Environment
Agency. \url{https://www.emisia.com/utilities/copert/documentation/}

\leavevmode\vadjust pre{\hypertarget{ref-r5r}{}}%
Pereira, R. H. M., Saraiva, M., Herszenhut, D., Braga, C. K. V., \&
Conway, M. W. (2021). r5r: Rapid realistic routing on multimodal
transport networks with R5 in r. \emph{Findings}.
\url{https://doi.org/10.32866/001c.21262}

\leavevmode\vadjust pre{\hypertarget{ref-ENMAC}{}}%
Presidência do Conselho de Ministros. (2019). Resolução do conselho de
ministros n.º 131/2019. In \emph{Diário da República, 1ª série} (Vol.
147, pp. 46--81).
\url{https://files.dre.pt/1s/2019/08/14700/0004600081.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-RIETVELD200071}{}}%
Rietveld, P. (2000). The accessibility of railway stations: The role of
the bicycle in the netherlands. \emph{Transportation Research Part D:
Transport and Environment}, \emph{5}(1), 71--75.
\url{https://doi.org/10.1016/S1361-9209(99)00019-X}

\leavevmode\vadjust pre{\hypertarget{ref-EuropeanCommission2014}{}}%
Sartori, D., Catalano, G., Genco, M., Pancotti, C., Sirtori, E.,
Vignetti, S., \& Del Bo, C. (2014). \emph{Guide to cost-benefit analysis
of investment projects. Economic apraisal tool for cohesion policy
2014-2020}. {European Commission - Directorate General for Regional and
Urban Policy}.
\url{https://ec.europa.eu/regional_policy/sources/docgener/studies/pdf/cba_guide.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-ANSR2021}{}}%
Silva, C., Bravo, J. V., \& Gonçalves, J. (2021). \emph{{Impacto
Económico e Social da Sinistralidade Rodoviária em Portugal}}. {Centro
de Estudos de Gestão do ISEG, Autoridade Nacional de Segurança
Rodoviária (ANSR)}.
\url{http://www.ansr.pt/Documents/Impacto_Economico_Social_Sinistralidade_Rodoviaria.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-Transtejo2014}{}}%
Transtejo. (2014). \emph{Relatório de sustentabilidade 2014}. {Grupo
Transtejo, S.A.}
\url{https://ttsl.pt/wp-content/uploads/2018/01/rs_2014_min.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-vanmil_insights_2021}{}}%
van Mil, J. F. P., Leferink, T. S., Annema, J. A., \& van Oort, N.
(2021). Insights into factors affecting the combined bicycle-transit
mode. \emph{Public Transport}, \emph{13}(3), 649--673.
\url{https://doi.org/10.1007/s12469-020-00240-2}

\end{CSLReferences}


\end{document}
