---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  out.width = "100%"
)
```
<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
library(sf)
```

# biclar

<!-- badges: start -->
<!-- badges: end -->

The goal of biclar is to store code and (in the releases) data for estimating cycling potential and influencing policy.

# Input data

The key datasets are as follows:

- [CAOP 2020](https://www.dgterritorio.gov.pt/cartografia/cartografia-tematica/caop?language=en) - Official limits of Portuguese areas.
- TRIPS_original.Rds, the original OD dataset, from INE (2018)


```{r}
od_all = readRDS("TRIPSmode_freguesias.Rds")
zones = readRDS("FREGUESIASgeo.Rds")
od_all_sf = od::od_to_sf(od_all, zones)
od_all_jittered = readRDS("od_all_jittered_50.Rds")
```

The OD datasets, before and after jittering, are shown below.

```{r jitteredoverview, out.width="50%", fig.show='hold'}
plot(od_all_sf$geometry, lwd = 0.2)
plot(od_all_jittered$geometry, lwd = 0.1)
```

