---
title: "Prototype"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# **DISCLAIMER**: This is a work in progress!

> The information contained in this website is a prototype that is being developed, tested, and consolidated, and the information is not binding on any institution or participant.  
Please do not share it with institutions or individuals outside the advisory process, or in any other way.


# **ATENÇÃO**: Isto não é uma versão final!

> A informação contida neste website constitui um protótipo em fase de desenvolvimento, testes e consolidação, e a sua informação não compromete qualquer entidade ou participante.  
Agradecemos que não seja partilhada com entidades ou individualidades externas ao processo consultivo, ou de qualquer outra forma.

This includes some statistics about each Municipality, and the Metro Region (*work in progress*).

The maps and statistics include: Baseline Scenario, ENMAC 4%, and ENMAC 10%.

**How to read the maps?**   

-   The line width is proportional to the number of cycling trips per day expected in each segment.
-   The darker the line is, less safe it is to cycle there (see [Quietness](https://www.cyclestreets.net/help/journey/howitworks/#quietness)), suggesting those cycling infrastructure should be provided there.

### Separated maps

*   **Área Metropolitana de Lisboa**: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/region_enmac10_fast.html)

*   Alcochete: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/alcochete_enmac10_fast.html)
*   Almada: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/almada_enmac10_fast.html)
*   Amadora: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/amadora_enmac10_fast.html)
*   Barreiro (*in july a new version of CycleStreets will improve these results*): 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/barreiro_enmac10_fast.html)
*   Cascais: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/cascais_enmac10_fast.html)
*   Lisboa: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/lisboa_enmac10_fast.html)
*   Loures: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/loures_enmac10_fast.html)
*   Mafra: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/mafra_enmac10_fast.html)
*   Moita: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/moita_enmac10_fast.html)
*   Montijo: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/montijo_enmac10_fast.html)
*   Odivelas: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/odivelas_enmac10_fast.html)
*   Oeiras: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/oeiras_enmac10_fast.html)
*   Palmela: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/palmela_enmac10_fast.html)
*   Seixal: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/seixal_enmac10_fast.html)
*   Sesimbra: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sesimbra_enmac10_fast.html)
*   Setubal: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/setubal_enmac10_fast.html)
*   Sintra: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/sintra_enmac10_fast.html)
*   Vila Franca de Xira: 
    +   Quiet routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_baseline_quiet.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_enmac4_quiet.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_enmac10_quiet.html)
    +   Fast routes: [Baseline](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_baseline_fast.html)    |   [ENMAC4](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_enmac4_fast.html)    |    [ENMAC10](https://ushift.tecnico.ulisboa.pt/content/tml/biclar/assets/vfxira_enmac10_fast.html)

